			{"allies"
				{title "Allies"}
				{armies "anz"}
				{armies "chn"}
				{armies "fra"}
				{armies "eng"}											
				{armies "rus"}
				{armies "usa"}								
				{icon "/interface/pages/multi/flag_allies"}
			}
            {"axis" 
				{title "Axis"}
                {armies "fin"}
				{armies "ger"}
                {armies "hun"}
                {armies "ita"}				
				{armies "jap"}				
				{icon "/interface/pages/multi/flag_axis"}
			}
			